### ISSUE TITLE
timestepExample - Still jittery

### ISSUE THREAD

**Issue by Ayymoose** [Hapaxia/Kairos#4]
Hi

I tried out your example by C&P ing to my project and change the fps to 60 but I'm still noticing some small jittering/stuttering regardless of using interpolation or extrapolation when  I use the keyboard to move the circle across the screen. Am I doing something wrong?

**Comment by Hapaxia** [comment]
Apologies for the delay. Are you still having this issue?

It's worth noting that stuttering can often be reduced using timestep/interpolation methods but cannot stop more serious reasons - most notably, operating system interference or graphics card/monitor update delays.
